---
- name: Deploy serivces
  hosts: all
  become_user: ansible
  remote_user: ansible
  vars:
    docker_registry_name: hannovernkmitte


  tasks:

    - name: Fail if deployment_version is missing
      fail:
        msg: "deployment_version is missing or empty"
      when: (deployment_version|length == 0)

    - name: Fail if telegram_access_token is missing
      fail:
        msg: "telegram_access_token is missing or empty"
      when: (telegram_access_token|length == 0)

    - name: Fail if directus_access_token is missing
      fail:
        msg: "directus_access_token is missing or empty"
      when: (directus_access_token|length == 0)


    - name: Deploy the TelegramBot
      docker_container:
        name: telegram-bot
        image: "{{ docker_registry_name }}/telegram-bot-help-ukrainian-refugees:{{ deployment_version }}"
        state: started
        recreate: yes
        restart_policy: always
        pull: true
        networks:
          - name: ukraine
        purge_networks: yes
        env: 
          Telegram:AccessToken: "{{ telegram_access_token }}"
          Directus:AccessToken: "{{ directus_access_token }}"
