# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
      include:
      - master
      - develop
  paths:
    include:
    - Source

pool:
  vmImage: ubuntu-latest

steps:

- task: DotNetCoreCLI@2
  displayName: Restore nugets
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/ChatBot/ChatBot.csproj'
    arguments: '-o $(System.DefaultWorkingDirectory)/binaries'
    zipAfterPublish: false

- task: Docker@2
  displayName: Build docker and push
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'hannovernkmitte/telegram-bot-help-ukrainian-refugees'
    command: 'buildAndPush'
    Dockerfile: '$(System.DefaultWorkingDirectory)/binaries/ChatBot/Dockerfile'
    buildContext: '$(System.DefaultWorkingDirectory)/binaries/ChatBot'

- task: PublishBuildArtifacts@1
  displayName: Publish deployment scripts to artifacts
  inputs:
    PathtoPublish: './Infrastructure/ansible/bot-deployment.yaml'
    ArtifactName: 'deployment'
    publishLocation: 'Container'